FruitAssociations:
  yami_yami: none
  mera_mera: none
  gura_gura: none
  moku_moku: none
  neko_neko_reoparudo: none
  magu_magu: none
  goro_goro: none
  ishi_ishi: none
  goru_goru: none
  inu_inu_okuchi: none
  ryu_ryu_allosaurs: none
  ope_ope: none
  zushi_zushi: none
hakiPlayers:
  TheWolf786:
      Level: 3
      Exp: 10

