name: OPhabs
version: '${project.version}'
main: htt.ophabs.OPhabs
commands:
  oph:
    description: Main command
api-version: 1.19
authors: [ RedRiotTank, MiixZ, Vaelico786 ]
website: https://github.com/RedRiotTank/OPhabs
